### ISSUE TITLE
Media Controls do not work properly on secondary monitor

### ISSUE THREAD

**Issue by sinus-x** [qwreey75/quick-settings-tweaks#54]
When two monitors are used, only the primary one has the Media Controls visible in the menu. On secondary monitor, it is still on the calendar tab.

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/236445280-8cd5ff10-cadf-482e-bbd9-cf9f3a8774af.png)

As gnome default, Second monitor doesn't have a panel.
If you use dash to panel extension (or sth creates a panel on second monitor) you can see panel on second monitor, which was created by extension

This means that actually we can't touch second monitor's panel menu, consider another extension [aztaskbar](https://gitlab.com/AndrewZaech/aztaskbar)
It also creates a panel in second monitor with different style classname
There is no way to get a second monitor's panel for each extension, sadly we can't config

But we can use some hacks, Almost extensions use imports.ui.panel.Panel to create a new panel and created panel will be inserted in Main.layoutManager.uiGroup.get_children() (we can check .name)

But this is very costly, init just one panel takes 50ms~90ms. if we configure all monitors, it will take almost 0.1 ~ 0.5 sec. THAT WILL SLOW DOWN LOCKSCREEN MUCH; not a good idea (lockscreen will disable/re-enable all extensions, and you will notice differ)

Also, it will be VERY complicated, extensions have no load order, what if dash to panel was disabled faster than QSTweaks? QSTweaks will fall unloading, gobjects destroyed already. and unlock lockscreen, QSTweaks will not load due to last error

btw, secondary monitor will be not supported (just dropped)
