### ISSUE TITLE
Gnome 44 Support

### ISSUE THREAD

**Issue by johnmmcgee** [qwreey75/quick-settings-tweaks#71]
Please port this to Gnome 44.

Thank you.

**Comment by loveisfoss** [comment]
I see that the last commit fro this repo is from December 2022. Has the development possibly been discontinued?

**Comment by Ticklezz** [comment]
I hope they are well and will continue to support this.

**Comment by kanansnote** [comment]
The upgrade is available. Hope that developers will take certain actions for adding the support, finally.

**Comment by johnmmcgee** [comment]
Awesome.  I saw your comment on gnome extensions.  If worse comes to worse we could fork the project and submit this as a new version.

**Comment by GatienVilain** [comment]
> Awesome. I saw your comment on gnome extensions. If worse comes to worse we could fork the project and submit this as a new version.

@kgdn suggested in a comment on gnome extensions to update to gnome 44 with this pull request https://github.com/qwreey75/quick-settings-tweaks/pull/78 , but since there doesn't seem to be any more activity on this repository, he also made a fork which is available at https://github.com/kgdn/quick-settings-tweaks . I don't know if he tried to propose it on gnome extension and I couldn't ask him. The issues seem to be disabled on his repository.

**Comment by kgdn** [comment]
> > Awesome. I saw your comment on gnome extensions. If worse comes to worse we could fork the project and submit this as a new version.
> 
> @kgdn suggested in a comment on gnome extensions to update to gnome 44 with this pull request #78 , but since there doesn't seem to be any more activity on this repository, he also made a fork which is available at https://github.com/kgdn/quick-settings-tweaks . I don't know if he tried to propose it on gnome extension and I couldn't ask him. The issues seem to be disabled on his repository.

Hi! Sorry about the delay, I've been very busy studying for upcoming exams but hopefully I can answer some of the questions you had. For starters, I am more than happy to upload the extension to GNOME Extensions. However I should make it known that I have little to no experience with actual extension development so I can't guarantee I'd be able to fix every issue that comes up. However, I can try my best. I'll look into uploading the extension on the extensions website later this week.

**Comment by kgdn** [comment]
Hi everyone, just wanted to update everyone very quickly. I made a last minute fix which positions the Do Not Disturb button above the background apps menu, which means the extension as far as I can see is 100% ready for GNOME 44. I've submitted the extension to the GNOME Extensions website under the name of 'Quick Settings Retweaked'. I will let everyone know of the outcome of the submission in the upcoming days.

**Comment by johnmmcgee** [comment]
Awesome!

**Comment by kgdn** [comment]
Hey everyone! Thankfully, the original author of the project has returned from his hiatus (also due to exams, so I can completely understand) and has merged the pull request I made. With that, everyone should continue to use the original extension over my fork, which will be archived soon. Thank you very much for understanding, and thank you to qwreey for making such a great extension!
